/*
 * ToDo API
 *
 * A simple ToDo API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// ToDoApiRouter defines the required methods for binding the api requests to a responses for the ToDoApi
// The ToDoApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ToDoApiServicer to perform the required actions, then write the service results to the http response.
type ToDoApiRouter interface { 
	TodosGet(http.ResponseWriter, *http.Request)
	TodosIdDelete(http.ResponseWriter, *http.Request)
	TodosIdGet(http.ResponseWriter, *http.Request)
	TodosIdPut(http.ResponseWriter, *http.Request)
	TodosPost(http.ResponseWriter, *http.Request)
}


// ToDoApiServicer defines the api actions for the ToDoApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type ToDoApiServicer interface { 
	TodosGet() (interface{}, error)
	TodosIdDelete(int32) (interface{}, error)
	TodosIdGet(int32) (interface{}, error)
	TodosIdPut(int32, Todo) (interface{}, error)
	TodosPost(Todo) (interface{}, error)
}
