name: Prepare Workflow
description: Prepare Workflow
runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
    - name: cache bundle
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Select Xcode15
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
    - name: bundle install
      shell: bash
      run: |
        set -ex
        
        gem install bundler:$(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -n 1 | awk '{$1=$1};1')
        bundle install