name: Prepare Workflow
description: Prepare Workflow
runs:
  using: "composite"
  steps:
    - name: install rbenv
      shell: bash
      run: |
        brew install rbenv
    - name: bundle isntall
      shell: bash
      run: |
        set -ex
        ruby=$(rbenv root)/versions$(cat .ruby-version)/bin/ruby
        
        if [ -e "$ruby" ]; them
          :
        else 
          rbenv install "$(cat .ruby-version)"
        fi
        
        gem install bundler:$(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -n 1 | awk '{$1=$1};1')
        bundle install