name: Prepare Google Cloud Service
description:  Prepare Google Cloud Service
runs:
  using: "composite"
  steps:
  - name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v1'
    id: gcs
    with:
      token_format: "access_token"
      workload_identity_provider: 'projects/308004819512/locations/global/workloadIdentityPools/githubactions/providers/github'
      service_account: 'githubaction@stellar-polymer-308508.iam.gserviceaccount.com'
#  - uses: 'google-github-actions/upload-cloud-storage@v1'
#    with:
#      path: 'DangerFile'
#      destination: 'bucket-name/file'
  - name: cat credentials
    shell: bash
    run: |
      cat ${{ steps.gcs.outputs.credentials_file_path }}