name: 'Install Xcode'
description: 'Installs a specified version of Xcode'
inputs:
  version:
    description: 'Version of Xcode to install'
    required: true
  apple-id:
    description: 'Apple Developer Account Id'
    required: true
  apple-id-password:
    description: 'Apple Developer Account Password'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u ${{ inputs.apple-id }} -p ${{ inputs.apple-id-password }}
        curl -LO "https://download.developer.apple.com/Developer_Tools/Xcode_${{ inputs.version }}/Xcode_${{ inputs.version }}.xip"
        # Extract Xcode
        xip -x Xcode_${{ inputs.version }}.xip
        # Move extracted Xcode app to Applications folder
        sudo mv Xcode.app /Applications/Xcode-${{ inputs.version }}.app
        # Switch to the installed Xcode
        sudo xcode-select -s /Applications/Xcode-${{ inputs.version }}.app/Contents/Developer
        # Verify the Xcode version
        xcodebuild -version
      shell: bash -xe {0}