name: branch_test
on:
  workflow_dispatch:
    inputs:
      bump:
        description: "bump"
        required: true
        default: false
        type: boolean
  pull_request:
  push:
      branches:
      - "*.*.*"
jobs:
  branch_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: bump
        if: github.event_name == 'push'
        run: |
          echo "bump"