name: chery pick
on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "commit hash"
        required: true
        type: string
jobs:
  chery_pick:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: chery pick
        run: |
          git cherry-pick -m 1 ${{ inputs.commit_hash }}
          git push origin ${{ github.head_ref }}