name: chery pick
on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "commit hash"
        required: true
        type: string
#  pull_request_target:

jobs:
  chery_pick:
    runs-on: ubuntu-latest
    steps:
      - name: echo xcode_version
        run: echo "### Build with Xcode ${{ inputs.commit_hash }} :hammer_and_pick:" >> $GITHUB_STEP_SUMMARY