name: unit_test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: true
        default: false
        type: boolean
  pull_request:

jobs:
  unit_testing:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare workflow
        uses: ./.github/actions/prepare_workflow
      - name: exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger