name: unit_test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "no use"
        required: true
        default: false
        type: boolean
  pull_request:

jobs:
  unit_testing:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare workflow
        uses: ./.github/actions/prepare_workflow
      - name: unit testing
        run: |
          cd iosApp
          bundle exec fastlane scan
      - name: exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}