name: unit_test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "no use"
        required: true
        default: false
        type: boolean
  pull_request:

env:
  DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"
  RUNTIMES_DIR: "/Library/Developer/CoreSimulator/Profiles/Runtimes"
  XCODES_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
  XCODES_USERNAME: ${{ secrets.APPLE_DEVELOPER_EMAIL }}

jobs:
  unit_testing:
    runs-on: macos-13
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: prepare workflow
        uses: ./.github/actions/prepare_workflow

      - name: prepare gcs
        uses: ./.github/actions/prepare_gcs

      - name: unit testing
        run: |
          cd iosApp
          bundle exec fastlane scan

      - name: exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger

# ワークフローが実行中に新しいコミットがプッシュされた場合は以前のワークフローを中断する
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true